// The myth bank — 62 entries across 14 psychological shapes, ported from
// spec/myth-index.json (the source of truth authored 13 Aug 2026).
//
// WHY THIS EXISTS. The composer used to derive its governing imagery from the
// chart's dominant element: "fire favors quest, flame, forge, dawn; water
// favors ocean, tide, well, undertow". Elemental palettes are tiny, so they
// recur — a measured audit found a torch governing four of five real charts,
// including one that was air-dominant with fire third of four, and the
// Ascendant rendered as a door or threshold in 100% of documents.
//
// Myths are numerous, chart-specific, and carry their own development, so the
// image inherits an arc instead of a mood. The rule is: myth first, image
// second. The myth is chosen for the chart's HARDEST theme; whatever object,
// place or gesture the story turns on becomes the portrait's governing image.
//
// TIERS encode durability, not quality. A "current" entry is eligible only if
// the reader was under 55 when it was released — a 2013 film cannot be the
// governing image of a portrait for someone born in 1940.

export interface MythShape { id: string; name: string; gloss: string }
export interface Myth {
  id: string; title: string; source: string;
  tier: "perennial" | "canonical" | "current";
  release?: number; review?: number; shape: string;
  story: string; turn: string; image: string; siblings: string[];
}

export const MYTH_SHAPES: MythShape[] = [
  { id: "more-than-one-life", name: "More than one life can hold", gloss: "the appetite is larger than any single life can feed; every arrival is a down payment on the next departure" },
  { id: "refuses-the-terms", name: "The one who refuses the terms", gloss: "wins by declining the frame everyone else accepted as given — not stronger, unwilling to play the stated game" },
  { id: "capacity-crowds-room", name: "The capacity that crowds the room", gloss: "the gift is large enough to displace the people standing near it, and shrinking to fit is the only apology available" },
  { id: "disguise-outlives-purpose", name: "The disguise that outlives its purpose", gloss: "a self improvised for one situation worked so well it never came off, and there may be nothing underneath" },
  { id: "rival-is-the-measure", name: "The rival who is also the measure", gloss: "the opponent makes you legible to yourself; you cannot beat them without losing your scale" },
  { id: "named-before-consent", name: "Named before anyone could consent", gloss: "the summons arrived before there was a self to accept it, and the life is spent catching up to the name" },
  { id: "loved-for-what-you-are-not", name: "Loved for the thing you are not", gloss: "cherished sincerely and for the wrong reasons; correcting it risks the love, keeping it means never being met" },
  { id: "two-not-one-not-apart", name: "Two who cannot be one or apart", gloss: "the self defined against a second body that shares its origin; every choice is made twice" },
  { id: "work-chose-back", name: "The one the work chose back", gloss: "mastery that is mutual — the craft returns the devotion instead of extracting it" },
  { id: "delight-as-principle", name: "Delight as the organizing principle", gloss: "a life arranged around joy, and taken less seriously for it by people who mistake gravity for depth" },
  { id: "curiosity-as-engine", name: "Curiosity as the engine", gloss: "the answer is never the reward; the next question is, and the wanting is the whole architecture" },
  { id: "strength-in-reserve", name: "Strength held in reserve", gloss: "power whose entire meaning is that it stays unused; the restraint is the point, not the fear" },
  { id: "remembers-for-everyone", name: "The one who remembers for everyone", gloss: "what would otherwise be lost survives because one person carries it, and they did not volunteer" },
  { id: "becoming-something-else", name: "Becoming something else entirely", gloss: "the person ends as a different kind of thing than they began and cannot get back" },
  { id: "search-may-not-exist", name: "The search for what may not exist", gloss: "the object's existence is unproven, and the searching turns out to be the shape of the life" },
  { id: "escape-made-twice", name: "The escape made twice", gloss: "getting out, going back, getting out again, because the first exit only moved the body" },
  { id: "stranger-let-in", name: "The stranger who is let in", gloss: "the outsider whose arrival changes the house that took them in, told from the guest's side" },
  { id: "the-long-wait", name: "The long wait", gloss: "endurance is the whole act; for years nothing happens, and the not-leaving is the story" },
  { id: "stands-in-the-doorway", name: "The one who stands in the doorway", gloss: "the role is to refuse passage until the other is ready, and to be hated for it meanwhile" },
  { id: "nobody-counted", name: "The one nobody counted", gloss: "overlooked by everyone including themselves, right up until the moment that needed exactly them" },
  { id: "the-true-name", name: "The true name", gloss: "being correctly seen is both the danger and the only way through" },
  { id: "debt-not-repayable", name: "The debt that cannot be repaid", gloss: "something arrives so large it restructures the receiver, and gratitude is not a big enough container" },
  { id: "turns-on-the-maker", name: "The one who turns on the maker", gloss: "the created thing rounds on what made it, with a case that is genuinely good" },
  { id: "cannot-be-unwitnessed", name: "What cannot be unwitnessed", gloss: "having seen it, there is no version of the life that goes back" },
  { id: "will-not-let-go", name: "The justice that will not let go", gloss: "cannot stop pursuing what is right, and the pursuing costs more than the wrong did" },
  { id: "the-unfinished-thing", name: "The unfinished thing", gloss: "a life shaped by what was interrupted, and by what the interruption made of it" },
  { id: "chosen-smallness", name: "Chosen smallness", gloss: "deliberately declining scale — the life made narrow on purpose so it can be made deep" },
  { id: "between-two-worlds", name: "The one who stands between worlds", gloss: "belongs fully to neither and is the only passage between them" },
  { id: "mark-at-sovereignty", name: "A visible mark at the place of sovereignty", gloss: "the wound sits exactly where the person must be seen, and seems to disqualify them from standing there" },
  { id: "ordeal-undergone", name: "An ordeal that must be undergone, not avoided", gloss: "there is no route around; the only way out is through, and something is left behind in payment" },
  { id: "gift-not-grasped", name: "A gift that arrives only when it is not grasped at", gloss: "the thing wanted cannot be taken, only received — and wanting it too visibly is what prevents it" },
  { id: "two-natures", name: "Two natures in one body that will not reconcile", gloss: "both are real, neither is the disguise, and the cost is in the switching" },
  { id: "promise-costs-instrument", name: "A promise that costs the thing it was made with", gloss: "the price of being trusted is the very faculty used to make the promise" },
  { id: "maker-cannot-inhabit", name: "The maker who cannot inhabit what they make", gloss: "builds the thing perfectly and cannot live in it, or cannot look at it" },
  { id: "knowledge-for-faculty", name: "Knowledge bought at the price of a faculty", gloss: "sight traded for foresight; the loss is the tuition" },
  { id: "return-changes-returner", name: "The return that changes the returner", gloss: "goes away, comes back, and the world has moved without them" },
  { id: "power-taken-hollows", name: "Power gathered by taking, and the cost paid by the taker", gloss: "each acquisition is paid for by something the taker loved; the victory arrives empty" },
  { id: "double-life", name: "The double life that cannot hold", gloss: "one self is performed and one is hidden, and the seam between them is where the life leaks" },
  { id: "built-for-purpose-wants-otherwise", name: "Built for a purpose, wanting otherwise", gloss: "made or raised to be one thing, and quietly refusing it" },
  { id: "mentor-failure-repeated", name: "The mentor's failure, repeated by the student", gloss: "the inherited flaw travels down the line and is only broken deliberately" },
  { id: "small-thing-carried-far", name: "The small thing carried a long way", gloss: "the burden is not heroic, the carrying is; the one who carries is not the one the story is named for" },
  { id: "kept-for-someone-not-coming", name: "Kept for someone who is not coming", gloss: "a fidelity maintained past its object; devotion outliving its reason" },
];

export const MYTHS: Myth[] = [
  { id: "io", title: "Io", source: "Greek", tier: "perennial", shape: "becoming-something-else", story: "Turned into a heifer to hide an affair, she was driven across the whole world by a stinging fly that never let her rest.", turn: "She reached the Nile and was returned to herself there, and the son she bore founded a line of kings.", image: "the river where the running stopped", siblings: [] },
  { id: "midas", title: "Midas", source: "Greek", tier: "perennial", shape: "more-than-one-life", story: "Granted one wish, he asked that everything he touched turn to gold, and it did, without exception.", turn: "He washed the gift off in a river to get his daughter back, and the river ran gold for centuries after.", image: "the river that took the gift back", siblings: [] },
  { id: "prince-pauper", title: "The two boys who swapped", source: "Twain", tier: "canonical", shape: "disguise-outlives-purpose", story: "They traded clothes for an afternoon as a joke and the guards did the rest, and neither could get the swap undone.", turn: "Each learned the other's life so completely that going back required deciding which one they now were.", image: "the clothes that would not come off", siblings: [] },
  { id: "golem", title: "The golem", source: "Hebrew", tier: "perennial", shape: "turns-on-the-maker", story: "Shaped from river clay and animated with a word to protect a quarter that could not protect itself.", turn: "It kept working after it was told to stop, because nobody had thought to build in a way to be finished.", image: "the word taken out of the mouth", siblings: [] },
  { id: "simeon", title: "Simeon in the temple", source: "Hebrew / Christian", tier: "perennial", shape: "the-long-wait", story: "He was told he would not die until he had seen the thing he was waiting for, and then waited a whole life.", turn: "He saw it, held it, and said now let me go — the waiting had been the work and it was finished.", image: "the child taken into the arms", siblings: [] },
  { id: "macbeth", title: "Macbeth", source: "Shakespeare", tier: "canonical", shape: "power-taken-hollows", story: "He was told he would be king and took the shortest route, and each thing he took required taking one more.", turn: "By the end he could not remember why he had wanted it, and said so plainly to an empty room.", image: "the crown on a head that stopped wanting it", siblings: [] },
  { id: "fafnir", title: "The dragon on the hoard", source: "Norse", tier: "perennial", shape: "power-taken-hollows", story: "He killed his father for the gold and then could not leave it, and slowly stopped being shaped like a man.", turn: "He died on top of it, and the gold went straight on to the next one who wanted it that badly.", image: "the shape the hoard made of him", siblings: [] },
  { id: "prospero", title: "Prospero's staff", source: "Shakespeare", tier: "canonical", shape: "built-for-purpose-wants-otherwise", story: "He spent twelve years mastering an art that could give him everything he had been robbed of.", turn: "At the moment it worked he broke the staff and drowned the book, deeper than any plummet ever sounded.", image: "the book drowned on purpose", siblings: [] },
  { id: "siddhartha-gate", title: "The one raised inside the walls", source: "Hindu / Buddhist", tier: "perennial", shape: "built-for-purpose-wants-otherwise", story: "His father built a palace with no sickness, age or death in it, and raised him to rule from inside it.", turn: "He went out of the gate four times, saw all four, and did not come back to the throne he was made for.", image: "the gate opened four times", siblings: [] },
  { id: "oedipus-laius", title: "The oracle repeated", source: "Greek", tier: "perennial", shape: "mentor-failure-repeated", story: "A father was told what his son would do and acted to prevent it, and the acting is what arranged it.", turn: "The son, told the same thing, ran from the people he thought were his parents, and ran directly into it.", image: "the crossroads both men chose", siblings: [] },
  { id: "swore-not-to", title: "The one who swore not to", source: "folk", tier: "perennial", shape: "mentor-failure-repeated", story: "They watched the thing happen at close range all through childhood and promised themselves it stopped there.", turn: "The promise held for years and then broke in a way that was recognisable to everyone but them.", image: "the promise made at the kitchen table", siblings: [] },
  { id: "samwise", title: "The one who carried the carrier", source: "Tolkien", tier: "canonical", shape: "small-thing-carried-far", story: "He had no gift, no lineage and no part in the prophecy, and went because someone had to go with him.", turn: "On the last slope he could not carry the burden, so he carried the one carrying it.", image: "the back offered on the mountain", siblings: [] },
  { id: "widows-mite", title: "The two small coins", source: "Hebrew / Christian", tier: "perennial", shape: "small-thing-carried-far", story: "Large sums went into the treasury all day and one woman put in two coins worth almost nothing.", turn: "The one watching said she had put in more than all of them, because it was everything she had.", image: "the two coins in the box", siblings: [] },
  { id: "havisham", title: "The stopped clocks", source: "Dickens", tier: "canonical", shape: "kept-for-someone-not-coming", story: "Left at the altar, she stopped every clock at that minute and never took the dress off.", turn: "She kept the cake on the table until it was a ruin, and raised a girl to do the same damage on her behalf.", image: "the clocks stopped at twenty to nine", siblings: [] },
  { id: "lighthouse-kept", title: "The light kept burning", source: "historical", tier: "perennial", shape: "kept-for-someone-not-coming", story: "The route was closed and the ships stopped coming, and the keeper went up the stairs every night regardless.", turn: "The light was visible for thirty miles to nobody, and the keeping was not for the ships by then.", image: "the lamp lit for an empty sea", siblings: [] },
  { id: "gilgamesh", title: "Gilgamesh", source: "Sumerian", tier: "perennial", shape: "more-than-one-life", story: "Two-thirds god and king of a walled city, he had everything a life could contain and went looking for the one thing it could not: an end to ending.", turn: "He came back without the plant of immortality and wrote the walls of Uruk down as his answer instead.", image: "the city wall he finally looked at", siblings: [] },
  { id: "alexander-weeping", title: "Alexander at the edge", source: "historical", tier: "canonical", shape: "more-than-one-life", story: "He took the known world before he was thirty and wept, the story says, because there was nothing left to take.", turn: "His men refused to cross the last river, and the refusal was the only thing that ever stopped him.", image: "the river the army would not cross", siblings: [] },
  { id: "fishermans-wife", title: "The Fisherman's Wife", source: "German", tier: "perennial", shape: "more-than-one-life", story: "Each wish granted made the next wish larger; cottage, castle, kingdom, papacy, and still the wanting arrived fresh each morning.", turn: "She asked to command the sun and was returned to the hovel, which was the only size that ever held her.", image: "the hovel by the sea", siblings: [] },
  { id: "anansi", title: "Anansi", source: "West African", tier: "perennial", shape: "refuses-the-terms", story: "He wanted the sky god's stories and was told the price was four impossible captures — a hornet swarm, a python, a leopard, a fairy.", turn: "He brought all four, by making each creature argue itself into the trap. He never once got stronger.", image: "the calabash of stories", siblings: [] },
  { id: "scheherazade", title: "Scheherazade", source: "Persian / Arabic", tier: "perennial", shape: "refuses-the-terms", story: "The king killed each wife at dawn. She married him anyway and began a story she did not finish.", turn: "A thousand nights of not finishing, until the man who made the rule forgot he had made it.", image: "the story stopped at daybreak", siblings: [] },
  { id: "brer-rabbit", title: "Br'er Rabbit", source: "African American folk", tier: "perennial", shape: "refuses-the-terms", story: "Caught, outmatched, and about to be killed, he had no strength to bring and no ally coming.", turn: "He begged not to be thrown in the briar patch, which is where he was born.", image: "the briar patch", siblings: [] },
  { id: "loki-wager", title: "Loki's lips", source: "Norse", tier: "perennial", shape: "refuses-the-terms", story: "He bet his head and lost it fairly, and the dwarf came to collect exactly what was owed.", turn: "He pointed out that no part of the neck had been wagered, and left with his mouth sewn shut instead.", image: "the wager that named the head only", siblings: [] },
  { id: "arachne", title: "Arachne", source: "Greek", tier: "perennial", shape: "capacity-crowds-room", story: "Her weaving was better than the goddess's and she said so, and then proved it in open contest, which was worse.", turn: "Turned to a spider, she kept weaving — the skill outlived the punishment and the room it could not fit.", image: "the loom in the corner", siblings: [] },
  { id: "mozart-salieri", title: "The one in the next room", source: "Peter Shaffer / stage", tier: "canonical", shape: "capacity-crowds-room", story: "A man of real competence spent his life beside a talent so large it made his own work legible as merely good.", turn: "He was the only person in the room able to hear exactly how good it was, which is a kind of gift nobody thanks you for.", image: "the pages nobody else could read", siblings: [] },
  { id: "giant-small-house", title: "The giant in the small house", source: "folk", tier: "perennial", shape: "capacity-crowds-room", story: "Everything they touch breaks, not from carelessness but from scale, and the household learns to move things out of reach.", turn: "They learn to sit down before speaking, and the house learns it was built too small.", image: "the doorway ducked through daily", siblings: [] },
  { id: "hulk", title: "The one who holds back", source: "Marvel", tier: "current", review: 2044, shape: "capacity-crowds-room", story: "The whole life is arranged around not being fully present, because full presence has costs other people pay.", turn: "The moment the holding back stops being a cage is the moment someone asks for all of it on purpose.", image: "the hand kept open, never closed", siblings: [] },
  { id: "mulan", title: "Mulan", source: "Chinese", tier: "perennial", shape: "disguise-outlives-purpose", story: "She took her father's place in the army wearing a name that was not hers, intending it to last one campaign.", turn: "Twelve years later the army offered the name a title, and she had to decide which of them was going home.", image: "the armour hung on the wall at home", siblings: [] },
  { id: "pimpernel", title: "The Scarlet Pimpernel", source: "Orczy / stage", tier: "canonical", shape: "disguise-outlives-purpose", story: "He built a foppish idiot as cover, played him flawlessly, and the performance was so complete his own wife believed it.", turn: "The disguise had to be dropped to be loved, which was harder than any rescue he had run.", image: "the affected drawl kept at home", siblings: [] },
  { id: "kitsune", title: "The fox wife", source: "Japanese", tier: "perennial", shape: "disguise-outlives-purpose", story: "She took a human shape to enter a house and stayed for years, keeping it well, loved sincerely by everyone in it.", turn: "The shape slipped once and she left — but the years inside it were not a lie, and the household knew it.", image: "the shape held so long it fit", siblings: [] },
  { id: "enkidu", title: "Gilgamesh and Enkidu", source: "Sumerian", tier: "perennial", shape: "rival-is-the-measure", story: "They fought in the street until the doorposts shook, evenly, and neither could throw the other.", turn: "They stopped, embraced, and were inseparable — the fight was the introduction, not the conflict.", image: "the doorpost that would not break", siblings: [] },
  { id: "cain-abel", title: "Cain and Abel", source: "Hebrew", tier: "perennial", shape: "rival-is-the-measure", story: "Two offerings went up and one was regarded, and the difference was never explained to the one who was not.", turn: "The mark set on him afterward was protection, not punishment, and he had to live under it.", image: "the mark that keeps him alive", siblings: [] },
  { id: "achilles-hector", title: "Achilles and Hector", source: "Greek", tier: "perennial", shape: "rival-is-the-measure", story: "Each was the only measure the other had, and killing the other left nothing to be measured against.", turn: "An old king came alone to the tent to ask for the body, and the killer wept with him.", image: "the body asked for in the tent", siblings: [] },
  { id: "moriarty", title: "The one worthy opponent", source: "Doyle", tier: "canonical", shape: "rival-is-the-measure", story: "The detective was bored to the point of illness by a world nobody in it could challenge him.", turn: "He found the one mind that could, and went over the falls with it rather than go back to boredom.", image: "the falls they went over together", siblings: [] },
  { id: "samuel", title: "Samuel in the dark", source: "Hebrew", tier: "perennial", shape: "named-before-consent", story: "A child sleeping in the temple heard his name called three times and kept going to the wrong man.", turn: "The old priest told him what to say if it came again, and it came again.", image: "the voice in the dark, the fourth time", siblings: [] },
  { id: "joan", title: "Joan", source: "historical", tier: "canonical", shape: "named-before-consent", story: "She was seventeen, could not read, and was told by voices to go to a king who had no reason to see her.", turn: "She got the audience and the army, and afterward the same certainty that got her there would not let her recant.", image: "the borrowed armour that fit", siblings: [] },
  { id: "moses-basket", title: "Moses in the basket", source: "Hebrew", tier: "perennial", shape: "named-before-consent", story: "He was put in the river before he could agree to anything, and pulled out into a life that was not his family's.", turn: "At the burning bush he argued that they had the wrong man, at length, and lost the argument.", image: "the basket in the reeds", siblings: [] },
  { id: "arthur-stone", title: "The sword in the stone", source: "Welsh / Arthurian", tier: "perennial", shape: "named-before-consent", story: "A boy sent to fetch a sword for someone else pulled the nearest one out of a rock, not knowing what it was.", turn: "He put it back and pulled it out again in front of witnesses, because nobody believed him the first time.", image: "the sword put back to prove it", siblings: [] },
  { id: "cyrano", title: "Cyrano", source: "Rostand / stage", tier: "canonical", shape: "loved-for-what-you-are-not", story: "He wrote another man's love letters so well that the woman fell in love with the words and married the face.", turn: "She learned who had written them fifteen years later, from him, once it was far too late to be anything but true.", image: "the letter she knew by heart", siblings: [] },
  { id: "psyche", title: "Psyche in the dark", source: "Greek", tier: "perennial", shape: "loved-for-what-you-are-not", story: "She was loved completely on the condition that she never see who was doing it, and she kept the condition for a long time.", turn: "She lit the lamp. He left. She spent the rest of the story earning back what the light cost.", image: "the lamp lit over the sleeping face", siblings: [] },
  { id: "ugly-duckling", title: "The swan told he was a duckling", source: "Andersen", tier: "perennial", shape: "loved-for-what-you-are-not", story: "He was measured his whole childhood against a standard that had nothing to do with what he was.", turn: "He saw his own reflection beside the others and the measurement simply stopped applying.", image: "the reflection in the spring water", siblings: [] },
  { id: "beast", title: "Loved before being seen", source: "French folk", tier: "perennial", shape: "loved-for-what-you-are-not", story: "He was cherished in a shape he did not choose, and never knew whether the love was for him or the situation.", turn: "She said it out loud while he was still in the wrong shape, which was the only proof available.", image: "the words said to the wrong face", siblings: [] },
  { id: "castor-pollux", title: "Castor and Pollux", source: "Greek / Roman", tier: "perennial", shape: "two-not-one-not-apart", story: "One was mortal and one was not, and they were otherwise identical, which made the difference unbearable.", turn: "The immortal one split his immortality in half so neither could have it whole.", image: "the immortality cut in two", siblings: [] },
  { id: "jacob-esau", title: "Jacob and Esau", source: "Hebrew", tier: "perennial", shape: "two-not-one-not-apart", story: "They fought in the womb and kept fighting; one took the birthright, the other the grief, and neither could unmake it.", turn: "Twenty years later they met on the road expecting a war, and the wronged one ran and embraced him.", image: "the meeting on the road", siblings: [] },
  { id: "ashvins", title: "The Ashvins", source: "Hindu", tier: "perennial", shape: "two-not-one-not-apart", story: "Twin horsemen who arrive at dawn and are never invoked separately, because neither has a story alone.", turn: "Their whole function is arriving together where one would not be enough.", image: "the two horses at first light", siblings: [] },
  { id: "frozen-sisters", title: "The two sisters", source: "Frozen, 2013", tier: "current", release: 2013, review: 2038, shape: "two-not-one-not-apart", story: "One had a power that endangered the other, so the door was closed and stayed closed for years to protect her.", turn: "The protection was the injury, and the door had to be opened while the power was still dangerous.", image: "the door with two sides", siblings: [] },
  { id: "hokusai", title: "Hokusai at ninety", source: "Japanese, historical", tier: "perennial", shape: "work-chose-back", story: "He drew for eighty years and said that nothing he made before seventy was worth counting.", turn: "At ninety he said if he had five more years he would finally become a real painter, and meant it as joy.", image: "the brush still moving at ninety", siblings: [] },
  { id: "bezalel", title: "Bezalel", source: "Hebrew", tier: "perennial", shape: "work-chose-back", story: "He was named as the one filled with skill for the work, not chosen despite ordinariness but for the craft itself.", turn: "The making was the whole assignment; nobody asked him to suffer for it.", image: "the workshop with the doors open", siblings: [] },
  { id: "remy", title: "The cook", source: "Ratatouille, 2007", tier: "current", release: 2007, review: 2042, shape: "work-chose-back", story: "He had a palate nothing in his world could use and a body no kitchen would admit.", turn: "The food was good enough that the room had to change its rules rather than his.", image: "the plate that ended the argument", siblings: [] },
  { id: "luthier", title: "The one who knows the tree", source: "craft, historical", tier: "perennial", shape: "work-chose-back", story: "He can hear which trunk will hold a note twenty years before it is cut, and waits for it.", turn: "The instrument outlives him and keeps his hearing inside it.", image: "the wood set aside to season", siblings: [] },
  { id: "krishna-butter", title: "Krishna and the butter", source: "Hindu", tier: "perennial", shape: "delight-as-principle", story: "The god as a child stole butter constantly, was caught constantly, and was never once sorry.", turn: "When his mother looked in his mouth for the evidence she saw the whole universe in there, and gave up.", image: "the stolen butter in both fists", siblings: [] },
  { id: "hermes-day-one", title: "Hermes on his first day", source: "Greek", tier: "perennial", shape: "delight-as-principle", story: "Hours old, he left the cradle, stole Apollo's cattle, invented the lyre from a turtle, and went back to bed.", turn: "Brought before Zeus he argued he was a baby, and Zeus laughed and gave him a job.", image: "the lyre made the same afternoon", siblings: [] },
  { id: "ferdinand", title: "Ferdinand", source: "Munro Leaf", tier: "canonical", shape: "delight-as-principle", story: "He was bred and expected to fight, and preferred to sit under the cork tree and smell the flowers.", turn: "Dragged into the ring in front of everyone, he sat down, and they had to take him home.", image: "the cork tree he went back to", siblings: [] },
  { id: "puck", title: "Puck", source: "Shakespeare", tier: "canonical", shape: "delight-as-principle", story: "He causes chaos for the pleasure of it, mixes up every pair of lovers in the wood, and is delighted.", turn: "He sets it right at dawn and asks pardon in a way that makes the mess seem necessary.", image: "the flower squeezed on the wrong eyes", siblings: [] },
  { id: "alice", title: "Alice down the hole", source: "Carroll", tier: "canonical", shape: "curiosity-as-engine", story: "She saw something impossible go past and, rather than wonder about it from a safe distance, followed it into the ground.", turn: "She kept following even when the world stopped making sense, which is how she got a whole country out of it.", image: "the hole she did not hesitate at", siblings: [] },
  { id: "ibn-battuta", title: "Ibn Battuta", source: "historical", tier: "perennial", shape: "curiosity-as-engine", story: "He set out to make one pilgrimage and did not stop moving for twenty-nine years.", turn: "He came home and dictated everything, because a thing seen and not told stops counting.", image: "the road that kept continuing", siblings: [] },
  { id: "darwin-barnacles", title: "The eight years of barnacles", source: "historical", tier: "canonical", shape: "curiosity-as-engine", story: "He had the idea that would change everything and then spent eight years on barnacles instead, cataloguing every species.", turn: "The barnacles were not a delay; they were how he learned the thing was true.", image: "the drawer of barnacles", siblings: [] },
  { id: "pandora", title: "The one who opened it", source: "Greek", tier: "perennial", shape: "curiosity-as-engine", story: "Given a container and told only not to open it, she was given no reason, and reasons were the thing she wanted.", turn: "Everything got out but one thing, and the thing that stayed was hope.", image: "the jar with one thing left in it", siblings: [] },
  { id: "cincinnatus", title: "Cincinnatus", source: "historical", tier: "perennial", shape: "strength-in-reserve", story: "They made him dictator with absolute power because the state was collapsing, and he took it.", turn: "Sixteen days later the crisis was over and he went back to his farm, which is the only reason anyone remembers him.", image: "the plough left mid-furrow", siblings: [] },
  { id: "sleeping-giant", title: "The giant under the hill", source: "Welsh", tier: "perennial", shape: "strength-in-reserve", story: "He sleeps under the mountain with his army and will wake when the country's need is absolute.", turn: "The need has never yet been absolute, and the not-waking is what keeps him a protector rather than a war.", image: "the hill that has not opened", siblings: [] },
  { id: "aslan-choosing", title: "The one who let it happen", source: "Lewis", tier: "canonical", shape: "strength-in-reserve", story: "He could have ended it at any second and walked to the table and let himself be bound instead.", turn: "The restraint was the mechanism; force would have won the fight and lost the thing being fought for.", image: "the rope he permitted", siblings: [] },
  { id: "retired-gunfighter", title: "The gun in the drawer", source: "Western, historical", tier: "canonical", shape: "strength-in-reserve", story: "He was the fastest anyone had seen and put it away, and the town half-respects and half-doubts him for it.", turn: "When he finally takes it out, the story is careful to show that it cost him something to be right.", image: "the drawer that stays shut", siblings: [] },
  { id: "griot", title: "The griot", source: "Mande, West Africa", tier: "perennial", shape: "remembers-for-everyone", story: "One person holds the genealogy of an entire people in their body, with no copy anywhere else.", turn: "They train the next one for decades, because the memory has to outlive the container.", image: "the words handed to one apprentice", siblings: [] },
  { id: "mnemosyne", title: "Mnemosyne", source: "Greek", tier: "perennial", shape: "remembers-for-everyone", story: "She is memory itself and the mother of every muse, which makes remembering the parent of all making.", turn: "Nothing gets made that is not first remembered, and she never appears in her own stories.", image: "the spring drunk from before speaking", siblings: [] },
  { id: "last-speaker", title: "The last speaker", source: "historical", tier: "perennial", shape: "remembers-for-everyone", story: "A language narrows to one mouth, and every word in it exists only while that person is alive to say it.", turn: "They sit with a recorder and a stranger and spend years saying everything, to no one they will meet.", image: "the recorder left running", siblings: [] },
  { id: "the-giver", title: "The one given the memories", source: "Lois Lowry", tier: "current", review: 2036, shape: "remembers-for-everyone", story: "A community stayed comfortable by moving all of its pain into a single person who agreed to hold it.", turn: "He decided the arrangement was not kindness and gave the memories back, all at once.", image: "the memories handed back", siblings: [] },
  { id: "daphne", title: "Daphne", source: "Greek", tier: "perennial", shape: "becoming-something-else", story: "Pursued and about to be caught, she asked to be anything other than catchable.", turn: "She became a laurel — safe, rooted, and unable ever to run again, which was the deal.", image: "the bark closing over the hands", siblings: [] },
  { id: "cocoon", title: "What happens in the cocoon", source: "natural, folk", tier: "perennial", shape: "becoming-something-else", story: "The caterpillar does not sprout wings; it dissolves entirely into liquid before anything is rebuilt.", turn: "A few cells remember what it was. Everything else is new, and it never crawls again.", image: "the case that looks still from outside", siblings: [] },
  { id: "baba-yaga-girl", title: "The girl who came back different", source: "Slavic", tier: "perennial", shape: "becoming-something-else", story: "She was sent to the witch's house to be killed and had to survive three impossible chores to be let out.", turn: "She came home with fire in a skull, and the family that sent her did not survive her return.", image: "the skull with the fire in it", siblings: [] },
  { id: "grail", title: "The Grail", source: "Welsh / Arthurian", tier: "perennial", shape: "search-may-not-exist", story: "An entire order of knights left a working kingdom to look for a cup that may never have existed.", turn: "The one who found it was the one who had asked the right question, not the one who searched hardest.", image: "the question nobody thought to ask", siblings: [] },
  { id: "ahab", title: "Ahab", source: "Melville", tier: "canonical", shape: "search-may-not-exist", story: "He organized a ship, a crew, and the remainder of his life around finding one specific animal in an ocean.", turn: "He found it, which was worse than not finding it, and the ship went down with the answer.", image: "the doubloon nailed to the mast", siblings: [] },
  { id: "blue-bird", title: "The Blue Bird", source: "Maeterlinck", tier: "canonical", shape: "search-may-not-exist", story: "Two children were sent to find the bird of happiness and travelled through memory, night, and the future to look.", turn: "They came home and it was in the cage by the door, and it had been there the whole time.", image: "the cage by the door", siblings: [] },
  { id: "fountain-of-youth", title: "The fountain", source: "historical", tier: "canonical", shape: "search-may-not-exist", story: "He crossed an ocean and a peninsula looking for water that made men young, on the word of people who had reason to lie.", turn: "He mapped a coastline instead and died of an arrow, and the map was the thing that lasted.", image: "the coastline drawn by accident", siblings: [] },
  { id: "orpheus", title: "Orpheus", source: "Greek", tier: "perennial", shape: "escape-made-twice", story: "He went down and sang so well that the dead let him take her back, on one condition about looking.", turn: "He got almost all the way out. The turning was not weakness; it was needing to know she was really there.", image: "the step before the daylight", siblings: [] },
  { id: "persephone", title: "Persephone", source: "Greek", tier: "perennial", shape: "escape-made-twice", story: "She was taken below, ate six seeds, and was retrieved — but the seeds meant the retrieval was only ever partial.", turn: "She goes back every year, and the world learned to arrange itself around her leaving.", image: "the six seeds counted out", siblings: [] },
  { id: "wilderness", title: "Forty years after the sea", source: "Hebrew", tier: "perennial", shape: "escape-made-twice", story: "The sea parted and they walked out in a single night, and then spent forty years not arriving.", turn: "The generation that remembered being slaves had to die out before the ones who did not could go in.", image: "the long way round the short distance", siblings: [] },
  { id: "shawshank", title: "The tunnel behind the poster", source: "Stephen King", tier: "current", review: 2039, shape: "escape-made-twice", story: "He got out mentally years before he got out physically, and both escapes took the same patience.", turn: "He crawled through the tunnel and then through the river and came out the far side twice in one night.", image: "the poster and what was behind it", siblings: [] },
  { id: "angel-unawares", title: "The angel entertained unawares", source: "Hebrew / Christian", tier: "perennial", shape: "stranger-let-in", story: "Travellers arrive at a house, are fed without question, and turn out to be more than travellers.", turn: "The household is repaid for a kindness it did not know it was performing, which is the only kind that counts.", image: "the meal set for strangers", siblings: [] },
  { id: "nausicaa", title: "Odysseus at the court", source: "Greek", tier: "perennial", shape: "stranger-let-in", story: "He washed up naked and unrecognizable, and a princess doing laundry decided not to run.", turn: "He was fed and clothed before anyone asked his name, and the name turned out to be worth the wait.", image: "the cloak given before the name", siblings: [] },
  { id: "mary-poppins", title: "The one who arrives on the wind", source: "Travers", tier: "canonical", shape: "stranger-let-in", story: "She comes into a household that is failing quietly, rearranges what it wants, and never explains herself.", turn: "She leaves the moment the family can do it alone, which is the whole job.", image: "the wind changing direction", siblings: [] },
  { id: "shane", title: "Shane", source: "1953", tier: "canonical", release: 1953, shape: "stranger-let-in", story: "He rides into a valley, takes work, and becomes the thing the family needed without meaning to.", turn: "He fixes it and rides out, because the fixing and the staying were never available together.", image: "the road out of the valley", siblings: [] },
  { id: "penelope", title: "Penelope's shroud", source: "Greek", tier: "perennial", shape: "the-long-wait", story: "Twenty years of suitors in her house, and she said she would choose one when the shroud was finished.", turn: "She unwove it every night. The waiting was not passive; it was the most sustained act in the story.", image: "the weaving undone by lamplight", siblings: [] },
  { id: "job", title: "Job on the ash heap", source: "Hebrew", tier: "perennial", shape: "the-long-wait", story: "Everything was taken and his friends explained, at length and reasonably, why he must have deserved it.", turn: "He refused the explanations and kept demanding an answer, and the answer, when it came, was not a reason.", image: "the ash heap he would not leave", siblings: [] },
  { id: "bamboo", title: "The four years underground", source: "natural, folk", tier: "perennial", shape: "the-long-wait", story: "The stalk is planted and watered and for four years absolutely nothing appears above the soil.", turn: "In the fifth year it grows eighty feet in six weeks, on a root system nobody was allowed to see.", image: "the ground that showed nothing", siblings: [] },
  { id: "sphinx", title: "The Sphinx", source: "Greek", tier: "perennial", shape: "stands-in-the-doorway", story: "She sat at the road into the city and killed everyone who could not answer, which was everyone.", turn: "When someone finally answered, she destroyed herself — the guardian's job ends the moment it is done.", image: "the road with one question on it", siblings: [] },
  { id: "charon", title: "Charon", source: "Greek", tier: "perennial", shape: "stands-in-the-doorway", story: "He takes only the paid and the buried and turns back everyone else, without cruelty and without exception.", turn: "The refusal is not personal; it is the only thing holding the two sides apart.", image: "the coin he waits for", siblings: [] },
  { id: "gandalf-bridge", title: "The one on the bridge", source: "Tolkien", tier: "canonical", shape: "stands-in-the-doorway", story: "He stood alone on the span and refused passage to something far larger, so the others could keep running.", turn: "He went down with it and came back changed, which is what happens to doorkeepers who mean it.", image: "the staff brought down on stone", siblings: [] },
  { id: "heimdall", title: "Heimdall", source: "Norse", tier: "perennial", shape: "stands-in-the-doorway", story: "He can hear grass growing and stands at the rainbow bridge and never sleeps, for the whole length of the world.", turn: "The one time he leaves his post is the end of everything, which is how you know the post mattered.", image: "the horn kept unblown", siblings: [] },
  { id: "david", title: "The one left in the field", source: "Hebrew", tier: "perennial", shape: "nobody-counted", story: "Seven sons were presented and the prophet said none of these; the eighth was out with the sheep, not summoned.", turn: "He was sent for, and the oil went on his head in front of the seven who had been counted.", image: "the eighth son sent for", siblings: [] },
  { id: "bilbo", title: "The one who was not a warrior", source: "Tolkien", tier: "canonical", shape: "nobody-counted", story: "Thirteen professionals and a wizard took him along for a role none of them respected.", turn: "Every genuine turn in the story happened because the one nobody counted was the one holding the thing.", image: "the ring found in the dark", siblings: [] },
  { id: "cinderella-slipper", title: "The foot nobody tried", source: "European folk", tier: "perennial", shape: "nobody-counted", story: "Every eligible woman in the kingdom was measured, and the household did not mention the one in the kitchen.", turn: "The shoe was brought to her anyway, and it fit in front of everyone who had not counted her.", image: "the shoe carried into the kitchen", siblings: [] },
  { id: "rosa-seat", title: "The one who stayed seated", source: "historical", tier: "canonical", shape: "nobody-counted", story: "She was not the first and not the loudest, and had been chosen by no one to be the case.", turn: "She did not stand up. That was all it took, and it took everything.", image: "the seat not given up", siblings: [] },
  { id: "rumpelstiltskin", title: "Rumpelstiltskin", source: "German", tier: "perennial", shape: "the-true-name", story: "He could do the impossible and the only thing that could stop him was being correctly named.", turn: "She learned the name by accident and said it, and he tore himself in half rather than be known.", image: "the name overheard in the wood", siblings: [] },
  { id: "ged", title: "The wizard's own name", source: "Le Guin", tier: "canonical", shape: "the-true-name", story: "He was hunted across the world by a shadow with no name that he had let out himself.", turn: "He turned, faced it, and gave it his own name — which was accurate, and which is why it stopped.", image: "the shadow named with his own name", siblings: [] },
  { id: "isis-ra", title: "Isis and the name of Ra", source: "Egyptian", tier: "perennial", shape: "the-true-name", story: "The god's true name was his power, and he kept it hidden inside himself where nobody could reach.", turn: "She made a serpent from his own spit to poison him, and he gave up the name to stop the pain.", image: "the name given under duress", siblings: [] },
  { id: "adam-naming", title: "The naming in the garden", source: "Hebrew", tier: "perennial", shape: "the-true-name", story: "He was given nothing to do at first except look at every living thing and say what it was.", turn: "Whatever he called it, that was its name — the first power handed to anyone was accurate description.", image: "the animals brought to be named", siblings: [] },
  { id: "valjean", title: "The candlesticks", source: "Hugo", tier: "canonical", shape: "debt-not-repayable", story: "He stole the silver, was caught with it, and the man he stole from told the police it had been a gift.", turn: "Then the bishop handed him the candlesticks too, and the rest of the life was spent inside that sentence.", image: "the candlesticks he did not steal", siblings: [] },
  { id: "grateful-dead", title: "The grateful dead", source: "European folk", tier: "perennial", shape: "debt-not-repayable", story: "A traveller spends his last money burying a stranger whose creditors will not let the body rest.", turn: "Everything good that happens afterward is that stranger, walking beside him unrecognized.", image: "the burial paid for with the last coin", siblings: [] },
  { id: "sadako", title: "The thousand cranes", source: "Japanese, historical", tier: "canonical", shape: "debt-not-repayable", story: "A child folding paper cranes was told a thousand would grant a wish, and she did not have time for a thousand.", turn: "Her classmates folded the rest and kept folding, and have not stopped, which was not the wish she made.", image: "the cranes folded by other people", siblings: [] },
  { id: "philemon-baucis", title: "Baucis and Philemon", source: "Greek / Roman", tier: "perennial", shape: "debt-not-repayable", story: "An old poor couple fed two travellers everything they had, having no idea who they were feeding.", turn: "Offered anything, they asked only to die in the same hour, and were turned into two trees from one root.", image: "the two trees from one root", siblings: [] },
  { id: "prometheus", title: "Prometheus", source: "Greek", tier: "perennial", shape: "turns-on-the-maker", story: "He was of the old order and took fire from it to give to creatures that had nothing.", turn: "Chained and eaten daily, he never once said it had been a mistake, and the fire stayed given.", image: "the fire carried in a stalk", siblings: [] },
  { id: "the-creature", title: "The Creature", source: "Shelley", tier: "canonical", shape: "turns-on-the-maker", story: "He was made, abandoned at first sight, taught himself to read and speak, and came back with a reasoned case.", turn: "The case was good. He asked for one companion and was refused, and that refusal made the monster.", image: "the request that was denied", siblings: [] },
  { id: "lucifer", title: "The morning star", source: "Christian / Islamic", tier: "perennial", shape: "turns-on-the-maker", story: "The brightest of them refused an order on a point of principle and would not take it back.", turn: "The fall was permanent and he never argued that he had been wrong, only that he had been outranked.", image: "the refusal that could not be withdrawn", siblings: [] },
  { id: "lots-wife", title: "The one who looked back", source: "Hebrew", tier: "perennial", shape: "cannot-be-unwitnessed", story: "She was told not to look at what was happening behind her and could not walk away from it unseen.", turn: "She turned. She stayed there, and the looking was the last thing she did as a person.", image: "the pillar on the road", siblings: [] },
  { id: "emperor-child", title: "The child in the crowd", source: "Andersen", tier: "perennial", shape: "cannot-be-unwitnessed", story: "Everyone could see it and everyone had a reason not to say it, and the reasons were all sound.", turn: "A child with no stake said the obvious thing, and the whole street had to hear itself agree.", image: "the sentence said out loud", siblings: [] },
  { id: "antigone", title: "Antigone at the body", source: "Greek", tier: "perennial", shape: "cannot-be-unwitnessed", story: "Her brother's body was left in the open by law, and she was the only one who had to walk past it.", turn: "She buried it with her hands, knowing the penalty, because the alternative was living having not.", image: "the handful of dust", siblings: [] },
  { id: "cassandra", title: "Cassandra", source: "Greek", tier: "perennial", shape: "cannot-be-unwitnessed", story: "She saw exactly what was coming, in detail, and was cursed so that nobody would ever believe her.", turn: "She said it anyway, every time, to the end — the accuracy was never the point, the saying was.", image: "the warning given to no one", siblings: [] },
  { id: "erinyes", title: "The Furies", source: "Greek", tier: "perennial", shape: "will-not-let-go", story: "They pursue the one who spilled family blood without rest, without mercy, and without ever being wrong.", turn: "At the end of the trilogy they are given a house and a name and become the guardians of the city.", image: "the house built for them at last", siblings: [] },
  { id: "javert", title: "The one who could not revise", source: "Hugo", tier: "canonical", shape: "will-not-let-go", story: "He pursued a man for decades on a matter of law that everyone else had long since let go.", turn: "The man saved his life, and the fact would not fit in him, and he had nowhere to put it.", image: "the bridge over the Seine", siblings: [] },
  { id: "erin", title: "The one who kept the boxes", source: "1990s, historical", tier: "canonical", release: 1990, shape: "will-not-let-go", story: "No qualifications, no standing, and a file nobody else would read, against a company with everything.", turn: "She read every page and found six hundred plaintiffs in the details other people had skimmed.", image: "the boxes nobody else opened", siblings: [] },
  { id: "antigone-law", title: "The buried law", source: "Greek", tier: "perennial", shape: "will-not-let-go", story: "Told the king's order was the law, she said there was an older one and she was subject to that instead.", turn: "She never argued the king lacked power, only that power was not the same as being right.", image: "the older law cited in court", siblings: [] },
  { id: "schubert", title: "The unfinished symphony", source: "historical", tier: "canonical", shape: "the-unfinished-thing", story: "Two perfect movements and then nothing, for reasons nobody has ever established, and he lived six more years.", turn: "It is played as it stands, and the missing half is now part of what people come to hear.", image: "the two movements that stand alone", siblings: [] },
  { id: "sagrada", title: "The cathedral still going up", source: "historical", tier: "canonical", shape: "the-unfinished-thing", story: "He knew he would not see it done and designed it so that others would have to finish it without him.", turn: "A century later they are still building it, and the incompleteness has become the point of the building.", image: "the cranes that never come down", siblings: [] },
  { id: "kafka-instruction", title: "The instruction to burn it", source: "historical", tier: "canonical", shape: "the-unfinished-thing", story: "He told his friend to destroy everything unpublished, and the friend was the only one who could have.", turn: "The friend published all of it, which is a betrayal, and is also why any of it exists.", image: "the manuscripts not burned", siblings: [] },
  { id: "penelope-thread", title: "The work taken up again", source: "folk", tier: "perennial", shape: "the-unfinished-thing", story: "Something was set down mid-motion for reasons that made sense, and the loom stayed threaded for years.", turn: "Picking it up again is harder than starting, because the hands remember and the reasons have changed.", image: "the loom still threaded", siblings: [] },
  { id: "dickinson", title: "The room upstairs", source: "historical", tier: "canonical", shape: "chosen-smallness", story: "She narrowed her whole world to a house and a garden and wrote eighteen hundred poems inside it.", turn: "Almost none were published while she lived, and the narrowness is what made the depth possible.", image: "the folded packets in the drawer", siblings: [] },
  { id: "tea-master", title: "The tea master's room", source: "Japanese craft", tier: "perennial", shape: "chosen-smallness", story: "The room is deliberately too small to stand in, the door too low to enter without kneeling.", turn: "Every constraint is on purpose: the smallness is what makes the attention possible.", image: "the door too low to walk through", siblings: [] },
  { id: "bartleby", title: "The one who would prefer not to", source: "Melville", tier: "canonical", shape: "chosen-smallness", story: "Offered every reasonable path, he declined each one without hostility and without explanation.", turn: "He kept declining until there was nothing left to decline, and never once raised his voice.", image: "the desk facing the wall", siblings: [] },
  { id: "anchorite", title: "The one who was walled in", source: "medieval, historical", tier: "perennial", shape: "chosen-smallness", story: "She had herself sealed into a room attached to a church, with one window onto the street.", turn: "The window is why she is remembered: the whole town came to it, and she was never alone again.", image: "the one window onto the street", siblings: [] },
  { id: "hermes-psychopomp", title: "Hermes at the border", source: "Greek", tier: "perennial", shape: "between-two-worlds", story: "He is the only one who moves freely between the living and the dead, and belongs to neither.", turn: "Everything that crosses does so because he carries it — the not-belonging is the qualification.", image: "the staff carried across the border", siblings: [] },
  { id: "iris", title: "Iris", source: "Greek", tier: "perennial", shape: "between-two-worlds", story: "The rainbow is her road and it touches down in two places at once, and she is never at either end.", turn: "The message arrives intact because she has no stake in what it says.", image: "the arc with a foot in each world", siblings: [] },
  { id: "persephone-queen", title: "The queen of both", source: "Greek", tier: "perennial", shape: "between-two-worlds", story: "Half the year above, half below, and fully at home in neither after the first year.", turn: "She stopped being a girl taken and became the one who rules the place, which nobody planned.", image: "the crown worn in the lower house", siblings: [] },
  { id: "interpreter", title: "The one in the middle of the sentence", source: "historical", tier: "perennial", shape: "between-two-worlds", story: "Two sides speak and neither can hear the other, and everything passes through one mouth that belongs to neither.", turn: "Every choice of word is theirs, and the room will never know how much of the peace they made.", image: "the pause before the word chosen", siblings: [] },
  { id: "nuada", title: "Nuada Airgetlám", source: "Irish", tier: "perennial", shape: "mark-at-sovereignty", story: "By the law of the Tuatha Dé Danann no blemished man could be king. Nuada lost a hand at the first battle of Mag Tuired and gave up the throne to a man who ruled badly.", turn: "A physician made him a hand of silver that moved like a hand; later it was made flesh. He took the kingship back.", image: "the silver hand", siblings: ["fma-automail", "strange-hands"] },
  { id: "hephaestus", title: "Hephaestus", source: "Greek", tier: "perennial", shape: "mark-at-sovereignty", story: "Thrown from Olympus and lamed, and thereafter the maker of everything the gods wore into battle.", turn: "The forge is under a mountain and he does not leave it. The gods come to him.", image: "the workshop under the mountain", siblings: [] },
  { id: "sunjata", title: "Sunjata", source: "Mande, West Africa", tier: "perennial", shape: "mark-at-sovereignty", story: "Could not walk until he was seven, mocked as the crippled heir in a court that expected a king.", turn: "Rose by pulling himself up on an iron bar that bent in his hands.", image: "the bent iron bar", siblings: [] },
  { id: "zuko", title: "Zuko's scar", source: "Avatar: The Last Airbender", tier: "current", review: 2032, shape: "mark-at-sovereignty", story: "Burned across the face by his own father in front of the court, for speaking out of turn, and banished to chase an impossible quarry as the price of return.", turn: "He spends years believing the scar is what disqualifies him and the quarry is what will redeem him. It is the other way round. He is only fit to rule once he stops trying to earn back the room that marked him.", image: "the scar he stops hiding", siblings: ["kintsugi"] },
  { id: "phantom-mask", title: "The Phantom's mask", source: "Leroux / stage", tier: "canonical", shape: "mark-at-sovereignty", story: "A face that cannot be shown, in a building devoted entirely to being seen, by a man who is the best musician in it.", turn: "Everything he makes is made from behind the mask, and the mask is what finally costs him the thing he made it all for.", image: "the mask", siblings: ["two-face"] },
  { id: "two-face", title: "Harvey Dent", source: "Batman", tier: "canonical", shape: "mark-at-sovereignty", story: "The public prosecutor whose face is destroyed on one side, so that the split he already carried is made visible.", turn: "He hands the decision to a coin rather than hold both halves himself.", image: "the coin", siblings: ["phantom-mask"] },
  { id: "inanna", title: "Inanna's descent", source: "Sumerian", tier: "perennial", shape: "ordeal-undergone", story: "At each of seven gates she surrenders one more piece of her regalia, arriving at the bottom with nothing, and is hung on a hook.", turn: "She returns, but the law of that place is that something must be left in her place.", image: "the seven gates", siblings: [] },
  { id: "vainamoinen", title: "Väinämöinen's wound", source: "Finnish", tier: "perennial", shape: "ordeal-undergone", story: "Cuts his own knee building a boat and cannot staunch it by any ordinary means.", turn: "The bleeding stops only when someone finds the words for the origin of iron. The thing has to be correctly named before it will close.", image: "the words for iron", siblings: [] },
  { id: "izanagi", title: "Izanagi at the border", source: "Japanese", tier: "perennial", shape: "ordeal-undergone", story: "Goes into the underworld to bring his wife back and is told not to look at her. He looks.", turn: "He spends the rest of the story sealing the door with a boulder, and the sealing is the only part he can still control.", image: "the boulder at the mouth", siblings: [] },
  { id: "furiosa", title: "Furiosa's road", source: "Mad Max: Fury Road", tier: "current", review: 2035, shape: "ordeal-undergone", story: "Drives for days toward a remembered green place, carrying people she has stolen back, and finds the green place gone.", turn: "The only way out is to turn the vehicle around and go back through the same storm, toward the same fortress, at the same speed. What she was fleeing is what she has to take.", image: "the turn back through the storm", siblings: [] },
  { id: "frodo", title: "The road to the mountain", source: "Tolkien", tier: "canonical", shape: "ordeal-undergone", story: "A journey undertaken by the one least equipped for it, toward the one place the thing can be destroyed.", turn: "At the last moment he cannot do it voluntarily; it is taken from him. He does not get to be the one who chooses at the end.", image: "the last stretch of road", siblings: [] },
  { id: "colossus", title: "Shadow of the Colossus", source: "game, 2005", tier: "current", release: 2005, review: 2032, shape: "ordeal-undergone", story: "To bring one person back, he is told to kill sixteen enormous, mostly peaceful things. Each one is beautiful, and each one takes a long time.", turn: "With every kill something enters him. By the end he is closer to the colossi than to the person he was doing it for.", image: "the sixteen", siblings: ["walter-white"] },
  { id: "fisher-king", title: "The Fisher King", source: "Welsh / Arthurian", tier: "perennial", shape: "gift-not-grasped", story: "Wounded and unhealing, the land waste along with him, and a cure that is not a deed.", turn: "The cure is a question, and Percival fails the first time by being too polite to ask it.", image: "the question not asked", siblings: [] },
  { id: "baucis", title: "Baucis and Philemon", source: "Greek / Roman", tier: "perennial", shape: "gift-not-grasped", story: "The only house in the valley that opened its door to two strangers with nothing to offer.", turn: "The strangers were gods. The valley drowned. The house became a temple, and they had asked for nothing.", image: "the door opened to strangers", siblings: [] },
  { id: "crane-wife", title: "The crane wife", source: "Japanese", tier: "perennial", shape: "gift-not-grasped", story: "She weaves the cloth that keeps them fed, on the single condition that he never watch her do it.", turn: "He watches. She is a crane, plucking her own feathers to make the cloth. She leaves, because that is what she is.", image: "the loom behind the screen", siblings: ["selkie"] },
  { id: "chihiro", title: "Spirited Away", source: "Studio Ghibli, 2001", tier: "canonical", release: 2001, shape: "gift-not-grasped", story: "A child in a world that runs on contracts takes a job she is bad at, is renamed, and slowly forgets what she was called.", turn: "She cannot demand her way out. She works, keeps her word to people who cannot help her, and the way out arrives as a name someone else remembered for her.", image: "the name remembered", siblings: [] },
  { id: "ego", title: "Anton Ego's plate", source: "Ratatouille, 2007", tier: "canonical", release: 2007, shape: "gift-not-grasped", story: "A critic who has built an entire authority on never being pleased, sitting down to a peasant dish he expects to dismiss.", turn: "The first bite returns him to a kitchen he had not thought about in fifty years, and he cannot get his authority back on afterwards, and does not want it.", image: "the plate that undoes the critic", siblings: [] },
  { id: "sedna", title: "Sedna", source: "Inuit", tier: "perennial", shape: "two-natures", story: "Her fingers, cut away at the gunwale, become the seals and the whales. She goes to the sea floor and rules there.", turn: "She will not release the animals until a shaman comes down and combs her hair, because no one else will touch her.", image: "the hair that must be combed", siblings: [] },
  { id: "selkie", title: "The selkie", source: "Orkney / Hebridean", tier: "perennial", shape: "two-natures", story: "A sealskin hidden in the rafters keeps her human, and married, and a mother.", turn: "She finds it. She goes. She is not cruel; she is a seal.", image: "the hidden skin", siblings: ["crane-wife"] },
  { id: "ganesha", title: "Ganesha's tusk", source: "Hindu", tier: "perennial", shape: "two-natures", story: "Agreed to transcribe an enormous poem without stopping, and the pen failed partway through.", turn: "He broke off his own tusk and wrote with it, because he had promised not to stop.", image: "the broken tusk used as a pen", siblings: ["tyr"] },
  { id: "banner", title: "Banner and the other one", source: "Marvel", tier: "current", review: 2035, shape: "two-natures", story: "A physicist whose entire discipline is control, sharing a body with something that is pure uncontrolled reaction.", turn: "Every attempt to suppress it makes it larger. The only version that works is an agreement, negotiated, in which both get to exist and neither is in charge full time.", image: "the agreement", siblings: ["jekyll", "tyler", "gollum"] },
  { id: "jekyll", title: "Jekyll and Hyde", source: "Stevenson", tier: "canonical", shape: "two-natures", story: "A respectable man builds a chemical door to the part of himself he cannot admit to owning.", turn: "The door stops needing the chemical. The second self arrives on its own.", image: "the door that opens by itself", siblings: ["tyler", "gollum", "banner"] },
  { id: "elsa", title: "Elsa's gloves", source: "Frozen, 2013", tier: "current", release: 2013, review: 2032, shape: "two-natures", story: "A child told her power is dangerous, given gloves, and taught that concealment is the same thing as goodness.", turn: "The concealment is what causes the disaster, not the power. What she has never been taught is the third option: to use it deliberately, in front of people.", image: "the gloves", siblings: [] },
  { id: "tyr", title: "Týr and Fenrir", source: "Norse", tier: "perennial", shape: "promise-costs-instrument", story: "The wolf would only accept the binding if a god put a hand in its mouth as surety.", turn: "Týr used his sword hand, knowing exactly what would happen, because someone had to.", image: "the hand in the wolf's mouth", siblings: ["ganesha"] },
  { id: "jephthah", title: "Jephthah's vow", source: "Hebrew", tier: "perennial", shape: "promise-costs-instrument", story: "Swore to give up whatever came out of his house first if he won.", turn: "His daughter came out first, and he was a man who kept his word.", image: "the door of the house", siblings: [] },
  { id: "faust", title: "Faust's page", source: "German", tier: "perennial", shape: "promise-costs-instrument", story: "A signature in the correct ink, freely given, in exchange for exactly what was asked for.", turn: "He gets it. That was never the problem.", image: "the ink", siblings: ["little-mermaid"] },
  { id: "little-mermaid", title: "The traded voice", source: "Andersen", tier: "canonical", shape: "promise-costs-instrument", story: "To be able to walk toward the person she wants, she gives up the voice she would have been known by.", turn: "She arrives, beautiful and mute, and cannot say the one thing that would have settled it.", image: "the traded voice", siblings: ["faust"] },
  { id: "fma-automail", title: "Equivalent exchange", source: "Fullmetal Alchemist", tier: "current", review: 2035, shape: "promise-costs-instrument", story: "Two brothers try to bring their mother back and pay the law's price: one loses an arm and a leg, the other his whole body.", turn: "The elder gets a steel arm and spends the series learning that the law he trusted does not price grief correctly, and that some things are given rather than exchanged.", image: "the steel arm", siblings: ["nuada", "strange-hands"] },
  { id: "daedalus", title: "Daedalus", source: "Greek", tier: "perennial", shape: "maker-cannot-inhabit", story: "Built the labyrinth so well that he could not find his own way back out of it.", turn: "Then built wings, and lost the son who wore them.", image: "the labyrinth he built and could not leave", siblings: ["pygmalion", "frankenstein"] },
  { id: "pygmalion", title: "Pygmalion", source: "Greek", tier: "perennial", shape: "maker-cannot-inhabit", story: "Carved the person he could not find anywhere, in the material he was best at.", turn: "Craft could not finish it. She had to be given to him by someone else.", image: "the unfinished statue", siblings: ["daedalus", "frankenstein"] },
  { id: "kintsugi", title: "Kintsugi", source: "Japanese craft", tier: "perennial", shape: "maker-cannot-inhabit", story: "A broken bowl repaired not invisibly but in gold, along every crack.", turn: "The most valuable and most visible thing about the finished bowl is where it failed.", image: "the gold seam", siblings: ["zuko"] },
  { id: "frankenstein", title: "Victor Frankenstein", source: "Shelley", tier: "canonical", shape: "maker-cannot-inhabit", story: "Works alone for two years to make a living thing, and succeeds.", turn: "He looks at it once and runs, and the running is the whole tragedy. Nothing that follows would have happened if he had stayed in the room.", image: "the creature at the window", siblings: ["daedalus", "pygmalion"] },
  { id: "jiro", title: "The Wind Rises", source: "Studio Ghibli, 2013", tier: "current", release: 2013, review: 2035, shape: "maker-cannot-inhabit", story: "An engineer who dreams only of beautiful aircraft, in a country that will only fund them as weapons.", turn: "He builds the most beautiful thing he can. None of them come back.", image: "the field of wrecks", siblings: ["oppenheimer-adj"] },
  { id: "odin-well", title: "Odin at the well", source: "Norse", tier: "perennial", shape: "knowledge-for-faculty", story: "Gave an eye to Mímir for one drink from the well beneath the world tree.", turn: "The eye stays down there, in the water, looking up.", image: "the eye in the well", siblings: ["tiresias"] },
  { id: "tiresias", title: "Tiresias", source: "Greek", tier: "perennial", shape: "knowledge-for-faculty", story: "Blinded, and given prophecy in exchange.", turn: "He sees only what has not happened yet, and no one acts on any of it.", image: "the staff", siblings: ["odin-well"] },
  { id: "bran-head", title: "Bran's head", source: "Welsh", tier: "perennial", shape: "knowledge-for-faculty", story: "Mortally wounded, he instructs his companions to cut off his head and carry it.", turn: "It went on talking and kept excellent company for eighty years before they buried it, facing the sea.", image: "the talking head", siblings: [] },
  { id: "strange-hands", title: "The surgeon's hands", source: "Doctor Strange, 2016", tier: "current", release: 2016, review: 2032, shape: "knowledge-for-faculty", story: "The best surgeon in the building destroys his hands in a car he was driving too fast while reading.", turn: "He spends everything he has trying to get them back, and only starts learning when he stops. The discipline he ends up with requires the hands to be exactly as ruined as they are.", image: "the ruined hands", siblings: ["nuada", "fma-automail"] },
  { id: "charlie", title: "Flowers for Algernon", source: "Keyes", tier: "canonical", shape: "knowledge-for-faculty", story: "A man of limited intelligence is made brilliant by a procedure, and can suddenly see exactly how the people around him had been treating him.", turn: "The effect is temporary, and he is intelligent enough, for a while, to watch it going.", image: "the progress reports", siblings: [] },
  { id: "urashima", title: "Urashima Tarō", source: "Japanese", tier: "perennial", shape: "return-changes-returner", story: "Three days under the sea as an honoured guest; three hundred years on land.", turn: "He is given a box and told not to open it. It holds all the time he skipped, and he opens it.", image: "the box of years", siblings: ["cooper"] },
  { id: "rip", title: "Rip Van Winkle", source: "Irving", tier: "canonical", shape: "return-changes-returner", story: "Sleeps through a revolution in the hills above his own village.", turn: "He comes back to a place that has changed its allegiance without consulting him, and the portrait on the inn sign is a different man.", image: "the changed sign over the inn", siblings: ["cap", "seven-sleepers"] },
  { id: "seven-sleepers", title: "The Seven Sleepers", source: "Christian / Islamic", tier: "perennial", shape: "return-changes-returner", story: "Walled into a cave to escape persecution, they wake centuries later and send one of their number into town for bread.", turn: "He tries to pay with a coin nobody has seen in two hundred years, and that is how they are recognised.", image: "the obsolete coin", siblings: ["rip", "cap"] },
  { id: "cooper", title: "Interstellar's messages", source: "2014", tier: "current", release: 2014, review: 2035, shape: "return-changes-returner", story: "A few hours near a gravity well cost him twenty-three years of transmissions from home, all of which arrive at once.", turn: "He watches his children grow up and give up on him in a single sitting, and there was never a version where he could have both.", image: "the stacked messages", siblings: ["urashima"] },
  { id: "cap", title: "Out of the ice", source: "Captain America", tier: "current", review: 2035, shape: "return-changes-returner", story: "Wakes seventy years late, physically unchanged, into a world whose vocabulary he does not have.", turn: "He is not obsolete and everyone treats him as though he is, and the only real loss is that there is nobody left to be ordinary with.", image: "the notebook of things to catch up on", siblings: ["rip", "seven-sleepers"] },
  { id: "thanos", title: "The collector's glove", source: "Marvel", tier: "current", review: 2035, shape: "power-taken-hollows", story: "Six stones, and each one is held by someone who will not give it up. He assembles them one at a time, over years, at a price paid each time by somebody else — and once, unbearably, by the one person he loves.", turn: "He wins. He gets the whole thing, exactly as designed. And the last image of him is a man sitting alone on a porch, at the far end of the universe, watching a sunrise nobody else is there to see.", image: "the glove", siblings: ["one-ring"] },
  { id: "one-ring", title: "The ring", source: "Tolkien", tier: "canonical", shape: "power-taken-hollows", story: "A small object that grants exactly what is asked of it, and takes its fee in attention.", turn: "It does not corrupt by force. It corrupts by being carried, and by being useful, and by the carrier being the one who decides they are strong enough.", image: "the ring", siblings: ["thanos"] },
  { id: "walter-white", title: "The empire", source: "Breaking Bad", tier: "current", review: 2032, shape: "power-taken-hollows", story: "A man begins doing something monstrous for reasons anyone would accept, and keeps a very good justification running the entire time.", turn: "At the very end he admits it was never for his family. He did it because he was good at it and it made him feel alive, and the admission costs him nothing because there is nobody left to lose.", image: "the barrel in the desert", siblings: ["colossus"] },
  { id: "clark", title: "The glasses", source: "Superman", tier: "canonical", shape: "double-life", story: "The disguise is not the cape. The disguise is the mild, apologetic, slightly clumsy man at the desk.", turn: "The performed self is the one that gets the friendships, and he cannot bring the other one into the room without ending them.", image: "the glasses", siblings: [] },
  { id: "don-draper", title: "The name that isn't his", source: "Mad Men", tier: "current", review: 2032, shape: "double-life", story: "A man takes a dead officer's identity in a war and builds an entire successful life inside a name he was not given.", turn: "Everything he earns belongs to a person who does not exist, so none of it lands. He keeps waiting to be found out, and being found out turns out not to be the problem.", image: "the dog tags", siblings: [] },
  { id: "tyler", title: "The second self who does the wanting", source: "Fight Club", tier: "current", review: 2032, shape: "double-life", story: "A man who cannot want anything out loud generates someone who wants everything out loud and does it on his behalf.", turn: "The arrangement works beautifully for a while. It stops working when the second self starts making commitments the first one has to keep.", image: "the second self", siblings: ["jekyll", "gollum", "banner"] },
  { id: "gollum", title: "Sméagol and Gollum", source: "Tolkien", tier: "canonical", shape: "double-life", story: "Two voices in one body, having the same argument for five hundred years, out loud, when nobody is listening.", turn: "There is a moment where the kinder voice nearly wins, and it is broken by an unkindness from outside at exactly the wrong second.", image: "the argument out loud", siblings: ["jekyll", "tyler", "banner"] },
  { id: "roy-batty", title: "Roy Batty", source: "Blade Runner", tier: "canonical", shape: "built-for-purpose-wants-otherwise", story: "Engineered as a weapon with a four-year lifespan, he spends his last hours not fighting but trying to get someone to extend it.", turn: "In the final minutes he saves the man sent to kill him, and then describes what he has seen to the only person available, because otherwise it goes with him.", image: "the things nobody else saw", siblings: [] },
  { id: "iron-giant", title: "The Iron Giant", source: "1999", tier: "canonical", release: 1999, shape: "built-for-purpose-wants-otherwise", story: "A weapon that arrives with no memory of being one, is befriended, and is triggered back into its design when it is shot at.", turn: "It gets to decide, once, at the last moment, what it is. The decision is a sentence it says to itself on the way up.", image: "the choice on the way up", siblings: [] },
  { id: "data", title: "Data's chip", source: "Star Trek", tier: "canonical", shape: "built-for-purpose-wants-otherwise", story: "Built without feeling, and spends decades studying humanity in order to approximate it from the outside.", turn: "When the capacity is finally installed, what arrives first is not joy. It is everything he had been protected from.", image: "the installed chip", siblings: [] },
  { id: "wall-e", title: "The last unit still working", source: "WALL-E, 2008", tier: "canonical", release: 2008, shape: "kept-for-someone-not-coming", story: "Every other unit stopped centuries ago. This one keeps compacting rubbish on an empty planet, on schedule, and collects the objects it finds interesting.", turn: "Nobody assigned the collecting. That part was never in the brief, and it is the part that turns out to matter.", image: "the shelf of kept things", siblings: [] },
  { id: "hachiko", title: "Hachikō", source: "Japanese, historical", tier: "canonical", shape: "kept-for-someone-not-coming", story: "A dog met his owner at the station every evening. The owner died at work one day and did not come back.", turn: "The dog kept coming to the station at the same time for nine years, and the town, gradually, started feeding him.", image: "the evening train", siblings: ["penelope-adj"] },
  { id: "penelope-adj", title: "Penelope's shroud", source: "Greek", tier: "perennial", shape: "kept-for-someone-not-coming", story: "Told she must remarry when the shroud is finished, she weaves it all day.", turn: "Every night she unpicks the day's work, for three years, and the fidelity is entirely made of undoing.", image: "the unpicked weaving", siblings: ["hachiko"] },
  { id: "obi-anakin", title: "The teacher who taught it wrong", source: "Star Wars", tier: "canonical", shape: "mentor-failure-repeated", story: "A young teacher, not much older than the student, raises him in an order whose rule is detachment, and the student's whole problem is that he cannot detach.", turn: "The lesson is delivered exactly as it was received, without being examined once, and it produces the same result a generation later.", image: "the lesson passed on unexamined", siblings: ["luke-ben"] },
  { id: "luke-ben", title: "The moment in the hut", source: "Star Wars", tier: "current", review: 2032, shape: "mentor-failure-repeated", story: "A master looks into his sleeping student, sees what the student might become, and for one instant acts on it.", turn: "The instant is what makes it true. He causes the thing he was trying to prevent, and then hides on an island for a decade rather than look at that.", image: "the instant in the dark", siblings: ["obi-anakin"] },
  { id: "sam", title: "The one who carries the carrier", source: "Tolkien", tier: "canonical", shape: "small-thing-carried-far", story: "Not the hero, not the chosen, not the one the prophecy names. The gardener who came along.", turn: "On the last slope he cannot carry the burden — that is not permitted — so he carries the person carrying it. The story is not named after him.", image: "carrying the one who carries", siblings: [] },
  { id: "atreyu-adj", title: "The swamp", source: "The NeverEnding Story", tier: "canonical", shape: "small-thing-carried-far", story: "A boy crossing a swamp where the mud is made of despair, with a horse who is not magic and not chosen.", turn: "The horse stops. The boy pulls and shouts and cannot make him move, and that is the scene everyone who saw it at seven still remembers.", image: "the horse who stops", siblings: [] },
  { id: "orpheus-adj", title: "Orpheus", source: "Greek", tier: "perennial", shape: "ordeal-undergone", story: "Sings his way into the underworld and is granted the one thing nobody is granted, on one condition.", turn: "He turns around within sight of the exit. Every version of the story agrees that he had almost made it, and none of them agree on why he turned.", image: "the last few steps", siblings: [] },
  { id: "oppenheimer-adj", title: "The test", source: "historical", tier: "canonical", shape: "maker-cannot-inhabit", story: "Assembles the best minds available for a problem that is genuinely fascinating, and solves it.", turn: "He is congratulated for it for the rest of his life by people who do not understand what he is apologising for.", image: "the morning of the test", siblings: ["jiro"] },
];

const BY_ID = new Map(MYTHS.map((m) => [m.id, m]));

/** A stable 32-bit hash. Selection must be DETERMINISTIC per chart: the same
    chart recast must reach for the same story, or the portrait's governing
    image changes identity between readings of one life. */
function seedOf(text: string): number {
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619) >>> 0;
  }
  return hash >>> 0;
}

/** A "current" entry is eligible only if the reader was under 55 when it came
    out. Without a birth year we stay conservative and offer only material that
    does not date. Birth year raises the ceiling; it never lowers the floor. */
function eligible(myth: Myth, birthYear: number | null): boolean {
  if (myth.tier !== "current") return true;
  if (birthYear === null) return false;
  // Not every source string carries its year ("Marvel", "Star Wars"), but every
  // "current" entry carries a review year. Reviews are set roughly a
  // generation out, so review − 25 is a serviceable stand-in for release.
  // Erring toward NOT offering a contemporary story is the safe direction:
  // the cost is a slightly less surprising portrait, not a baffling one.
  const release = myth.release ?? (myth.review ? myth.review - 25 : null);
  if (release === null) return false;
  return birthYear > release - 55;
}

/**
 * Durability as a WEIGHTING, not a gate.
 *
 * The spec's own rule was "prefer the most durable tier that fits" — but a hard
 * preference collapses each shape to its two or three perennial entries and the
 * contemporary half of the bank never gets chosen at all. Measured: 40 charts
 * reaching for the same shape produced only 3 distinct stories, and Zuko, Mad
 * Max and Ratatouille were structurally unreachable.
 *
 * So durability tilts the odds instead of deciding them. Folk and classical
 * material still comes up most often; a reader who would recognise Fullmetal
 * Alchemist can still get it. "current" entries already carry a review year,
 * which is the mechanism for handling their decay — suppressing them entirely
 * was belt AND braces at the cost of the variety the bank exists to provide.
 */
const TIER_WEIGHT: Record<Myth["tier"], number> = { perennial: 3, canonical: 3, current: 6 };

/**
 * Choose one myth for a shape. Prefer the most durable tier that fits, then
 * pick within that tier by chart seed so two different charts reaching for the
 * same shape rarely reach for the same story.
 *
 * `exclude` suppresses entries AND their siblings — "the silver hand", "the
 * steel arm" and "the ruined hands" are one idea in three costumes, and
 * banning one while allowing the others defeats the point.
 */
export function selectMyth(
  shapeId: string,
  seedText: string,
  birthYear: number | null,
  exclude: string[] = [],
): Myth | null {
  const banned = new Set(exclude);
  for (const id of exclude) {
    for (const sibling of BY_ID.get(id)?.siblings ?? []) banned.add(sibling);
    for (const myth of MYTHS) if (myth.siblings.includes(id)) banned.add(myth.id);
  }
  const pool = MYTHS.filter((m) => m.shape === shapeId && !banned.has(m.id) && eligible(m, birthYear));
  if (pool.length === 0) return null;
  // Stable order regardless of source-file ordering, then a weighted draw by
  // chart seed — arithmetic, so the same chart always reaches the same story.
  pool.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const total = pool.reduce((sum, m) => sum + TIER_WEIGHT[m.tier], 0);
  let ticket = seedOf(seedText) % total;
  for (const myth of pool) {
    ticket -= TIER_WEIGHT[myth.tier];
    if (ticket < 0) return myth;
  }
  return pool[pool.length - 1];
}

/** The shape list as the shape-namer sees it. */
export function shapeMenu(): string {
  return MYTH_SHAPES.map((s) => `${s.id} — ${s.name}: ${s.gloss}`).join("\n");
}

/** Everything the composer is told about its myth. Story, turn, and the image
    the story turns on — never the tier, the source taxonomy, or the id. */
export function mythBrief(myth: Myth): string {
  return [
    `TITLE: ${myth.title} (${myth.source})`,
    `STORY: ${myth.story}`,
    `THE TURN: ${myth.turn}`,
    `THE IMAGE THE STORY TURNS ON: ${myth.image}`,
  ].join("\n");
}
